version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: standup
      POSTGRES_PASSWORD: standup
      POSTGRES_DB: standup
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata:
